version: '3'
services:
 rabbit:
  image: "rabbitmq:3-management"
  restart: always
  hostname: "rabbit1"
  environment:
    RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
    RABBITMQ_DEFAULT_USER: "rabbitmq"
    RABBITMQ_DEFAULT_PASS: "rabbitmq"
    RABBITMQ_DEFAULT_VHOST: "/"
  ports:
    - "15672:15672"
    - "5672:5672"
  labels:
    NAME: "rabbitmq1"
  volumes:
    - ./RabbitMQ/enabled_plugins:/etc/rabbitmq/enabled_plugins
 redis:
  image: "redis:4.0-alpine"
  restart: always
  ports:
    - "6379:6379"
 redisCommander:
  image: tenstartups/redis-commander
  restart: always
  command: --redis-host redis
  links:
    - redis:redis
  ports:
    - "8081:8081"
